AllCops:
  TargetRubyVersion: 2.6.0
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
Metrics/ClassLength:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Metrics/AbcSize:
  Max: 20
